print("Hello, World!")
print("Welcome to MyPyproject!")
name = input("Please enter your name: ")
print(f"Nice to meet you, {name}!")
print(f"Hello, {name}! Glad to have you learning Python with MyPyproject!")
print("Let's get to know you better!")
age = input("How old are you? ")
print(f"Wow, {age} years old! That's great!")   
print("Thank you for sharing, " + name + "! Let's continue learning Python together!")
marrital_status = input("Are you married? (yes/no) ")
if marrital_status.lower() == "yes":
    print("Congratulations on your marriage, " + name + "!")    
else:    print("No worries, " + name + "! Being single has its perks too!")
print("Thank you for sharing, " + name + "! Let's continue learning Python together!")  
job = input("What do you do for a living? ")    
print(f"That's interesting, {name}! Being a {job} must be rewarding!")
print("Thank you for sharing, " + name + "! Let's stop here, we'll continue learning Python together soon!")
